spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapi_db?allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: MZtnjPMNp#12
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  packages-to-scan: com.alg.boot.webapi
  paths-to-match: /api/v1/**

logging:
  level:
    org.hibernate: DEBUG
