spring:
  devtools:
    add-properties: false
  application:
    name: webapi
  datasource:
    url: jdbc:mysql://localhost:3306/webapi_db?allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: MZtnjPMNp#12
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-wait-millis: 30000
      validation-query: "SELECT 1"
      validation-query-timeout: 30
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  data:
    rest:
      base-path: /api/v1/
      default-page-size: 20

springdoc:
  packages-to-scan: com.alg.boot.webapi
  paths-to-match: /api/**

logging:
  level:
    org.hibernate: DEBUG

server:
  port: 8080
