spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapi_db?allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: MZtnjPMNp#12
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  level:
    org.hibernate: DEBUG